#!/usr/bin/env bash

source __shared.sh

message='Initialize project'

printCommand "git init"
git init

printCommand "git add . -v"
git add . -v

printCommand "git commit -am \"$message\""
git commit -am "$message"

printCommand "git branch -m main"
git branch -m main
