#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/__shared.sh"

message=${1}

if [ -z "$message" ]; then
  echo "Usage: $(basename $0) <message>"
  exit 1
fi

__print_command_and_eval "git status -s"
__print_command_and_eval "git add . -v"
__print_command_and_eval "git commit -am "$message""
__print_command_and_eval "git push --all -v"
__print_command_and_eval "git push --tags -v"
