#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/__shared.sh"

repo=$(git config remote.origin.url)

print "[x] Copying origin URL: ${repo}"

printCommand "rm -rf .git/"
rm -rf .git/

printCommand "git setup"
print "■■■■■■■■■■■■■■■■■■"
git setup

printCommand "git config remote.origin.url ${repo}\n"
git config remote.origin.url ${repo}
