#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/__shared.sh"

printCommand "git config remote.origin.url"
git config remote.origin.url

printCommand "git status -sb"
git status -sb

printCommand "git branch --all -v"
git branch --all -v

printCommand "git tag -l"
git tag -l

printCommand "git pull -v"
git pull -v

printCommand "git fetch -pv"
git fetch -pv

printCommand "git push --all -v"
git push --all -v

printCommand "git push --tags -v"
git push --tags -v
