#!/usr/bin/env bash

source __shared.sh

msg='Initialize project'

print "[x] Run: git init"
git init

print "[x] Run: git add . -v"
git add . -v

print "[x] Run: git commit -am '$msg'"
git commit -am "$msg"

print "[x] Run: git branch -m main"
git branch -m main
