#!/usr/bin/env bash

echo -e "[x] Run: git config remote.origin.url\n"
git config remote.origin.url

echo -e "\n[x] Run: git status -sb\n"
git status -sb

echo -e "\n[x] Run: git branch --all\n"
git branch --all

echo -e "\n[x] Run: git tag -l\n"
git tag -l

echo -e "[x] Run: git pull\n"
git pull

echo -e "\n[x] Run: git fetch -p\n"
git fetch -p

echo -e "[x] Run: git push --all\n"
git push

echo -e "\n[x] Run: git push --tags\n"
git push --tags
