#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/__shared.sh"

message=$1
usage='Usage: git fire "MESSAGE"'

if [ -z "$message" ]; then
  echo "$usage"
  exit 1
fi

printCommand "git status -s"
git status -s

printCommand "git add . -v"
git add . -v

printCommand "git commit -am \"$message\""
git commit -am "$message"

printCommand "git push --all -v"
git push --all -v

printCommand "git push --tags -v"
git push --tags -v
