#!/usr/bin/env bash

source __shared.sh

repo=$(git config remote.origin.url)

print "[x] Copying origin URL: ${repo}"

print "[x] Run: rm -rf .git/"
rm -rf .git/

print "[x] Run: git setup"
print "■■■■■■■■■■■■■■■■■■"
git setup

print "[x] Run: git config remote.origin.url ${repo}\n"
git config remote.origin.url ${repo}
