#!/usr/bin/env bash

source __colors.sh

c=$__COLOR_GREEN
x=$__COLOR_RESET
repo=$(git config remote.origin.url)

echo -e "[x] Copying origin URL: ${c}${repo}${x}"

echo -e "[x] Run: ${c}rm -rf .git/${x}"
rm -rf .git/

echo -e "[x] Run: ${c}git setup${x}"
echo -e "■■■■■■■■■■■■■■■■■■"
git setup

echo -e "[x] Run: ${c}git config remote.origin.url ${repo}${x}\n"
git config remote.origin.url ${repo}
