#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/__shared.sh"

message=$1

if [ -z "$message" ]; then
  echo "Usage: $(basename $0) <message>"
  exit 1
fi

__print_command "git status -s"
git status -s
echo ""

__print_command "git add . -v"
git add . -v
echo ""

__print_command "git commit -am \"$message\""
git commit -am "$message"
echo ""

__print_command "git push --all -v"
git push --all -v
echo ""

__print_command "git push --tags -v"
git push --tags -v
echo ""
