#!/usr/bin/env node

const process = require("process");
const { runCommand, getProcessOptions } = require("./__shared");

const USAGE = `
    Usage: git changed-packages [--oneline] [--main]

    Examples:

        $ git changed-packages
        $ git changed-packages --oneline
        $ git changed-packages --main
`;

const GIT_DIFF_BRANCH = (branch = "master") =>
  `git diff ${branch}.. --name-only`;
const PACKAGES_PATH = /^packages\//;
const PACKAGE_NAME = /^packages\/([\w-]*)\/(.*)$/;

async function collectChangedPackages(branch) {
  const diff = await runCommand(GIT_DIFF_BRANCH(branch));
  const changedFiles = diff.split("\n");
  const onlyPackagesFiles = changedFiles.filter((x) => PACKAGES_PATH.test(x));
  const packages = onlyPackagesFiles.reduce((list, filename) => {
    const matched = filename.match(PACKAGE_NAME);
    if (Array.isArray(matched)) {
      const packageName = matched[1];
      list.add(packageName);
    }
    return list;
  }, new Set());
  return packages;
}

function displayOnelineResults(packages) {
  console.log([...packages].join(" "));
}

function displayResults(packages) {
  console.log("List of packages with changed files:");
  packages.forEach((name) => {
    console.log(`- ${name}`);
  });
}

async function main() {
  const options = getProcessOptions(process.argv);
  if (options.h || options.help) {
    console.log(USAGE);
    return void process.exit(0);
  }
  const branch = options.main ? "main" : "master";
  const packages = await collectChangedPackages(branch);
  const isOneline = options.oneline;

  if (isOneline) {
    displayOnelineResults(packages);
  } else {
    displayResults(packages);
  }
}

main().catch(console.error);
