#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/__shared.sh"

__print_command "git config remote.origin.url"
git config remote.origin.url
echo ""

__print_command "git status -sb"
git status -sb
echo ""

__print_command "git branch --all -v"
git branch --all -v
echo ""

__print_command "git tag -l"
git tag -l
echo ""

__print_command "git pull -v"
git pull -v
echo ""

__print_command "git fetch -pv"
git fetch -pv
echo ""

__print_command "git push --all -v"
git push --all -v
echo ""

__print_command "git push --tags -v"
git push --tags -v
echo ""
